In [1]:
#Cargando librerías a utilizar

from sklearn.neural_network import MLPClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

In [2]:
#Cargando el conjunto de datos Iris

iris = load_iris()
X, y = iris.data, iris.target 

In [7]:
#Explorando los datos
type(iris)
iris.keys()
print(iris['data'][:5])
print("******"*10)
print(iris['target'][:5])
print("******"*10)
print(iris['target_names'])
print("******"*10)
print(iris['DESCR'])
print("******"*10)
print(iris['feature_names'])


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
************************************************************
[0 0 0 0 0]
************************************************************
['setosa' 'versicolor' 'virginica']
************************************************************
.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84  

In [8]:
#Dividir los datos en entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#Escalando caracteristicas para un mejor rendimiento del modelo
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [9]:
#Creando instancia de MLPClassifier
mlp_clf = MLPClassifier(hidden_layer_sizes=(100), activation='relu', solver='adam', max_iter=100, random_state=42, verbose=True)

#Entrenando el modelo
mlp_clf.fit(X_train_scaled, y_train)

Iteration 1, loss = 1.16374923
Iteration 2, loss = 1.14090611
Iteration 3, loss = 1.11857816
Iteration 4, loss = 1.09677375
Iteration 5, loss = 1.07547149
Iteration 6, loss = 1.05468504
Iteration 7, loss = 1.03440573
Iteration 8, loss = 1.01462373
Iteration 9, loss = 0.99535820
Iteration 10, loss = 0.97658926
Iteration 11, loss = 0.95833257
Iteration 12, loss = 0.94053852
Iteration 13, loss = 0.92322169
Iteration 14, loss = 0.90638373
Iteration 15, loss = 0.89000670
Iteration 16, loss = 0.87408395
Iteration 17, loss = 0.85861030
Iteration 18, loss = 0.84357120
Iteration 19, loss = 0.82895431
Iteration 20, loss = 0.81476466
Iteration 21, loss = 0.80097410
Iteration 22, loss = 0.78759157
Iteration 23, loss = 0.77460302
Iteration 24, loss = 0.76199129
Iteration 25, loss = 0.74975377
Iteration 26, loss = 0.73786826
Iteration 27, loss = 0.72632581
Iteration 28, loss = 0.71511871
Iteration 29, loss = 0.70424319
Iteration 30, loss = 0.69368183
Iteration 31, loss = 0.68342580
Iteration 32, los

c:\Users\Simon R\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(hidden_layer_sizes=100, max_iter=100, random_state=42,
              verbose=True)

In [12]:
#Realizando predicciones con el conjunto de prueba
y_pred = mlp_clf.predict(X_test_scaled)
print(y_test)
print(y_pred)

#Calculando la precisión del modelo
accuracy = accuracy_score(y_test, y_pred)
print(f'Precisión del modelo: {accuracy*100:.2f}%')

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]
[1 0 2 1 2 0 1 2 1 1 2 0 0 0 0 2 2 1 1 2 0 2 0 2 2 2 2 2 0 0]
Precisión del modelo: 93.33%


#### Ejemplo de regresión con MLPRegressor de Scikit-Learn

In [13]:
#Cargando librerias extra a utilizar
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.datasets import fetch_california_housing
from sklearn.neural_network import MLPRegressor

#Cargando el conjunto de datos California Housing
housing = fetch_california_housing()
X, y = housing.data, housing.target

In [14]:
#Explorando los datos
type(housing)
print(housing['DESCR'])

.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

:Number of Instances: 20640

:Number of Attributes: 8 numeric, predictive attributes and the target

:Attribute Information:
    - MedInc        median income in block group
    - HouseAge      median house age in block group
    - AveRooms      average number of rooms per household
    - AveBedrms     average number of bedrooms per household
    - Population    block group population
    - AveOccup      average number of household members
    - Latitude      block group latitude
    - Longitude     block group longitude

:Missing Attribute Values: None

This dataset was obtained from the StatLib repository.
https://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html

The target variable is the median house value for California districts,
expressed in hundreds of thousands of dollars ($100,000).

This dataset was derived from the 1990 U.S. census, using one row per ce

In [31]:
#Dividir los datos en entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#Escalando caracteristicas
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

y_scaler = StandardScaler()
y_train_scaled = y_scaler.fit_transform(y_train.reshape(-1, 1))

In [32]:
#Creando instancia de MLPRegressor
mlp_reg = MLPRegressor(hidden_layer_sizes=(100), activation='relu', solver='adam', max_iter=100, random_state=42, verbose=True)

#Entrenando modelo
mlp_reg.fit(X_train_scaled, y_train_scaled)

#Realizando predicciónes
y_pred = mlp_reg.predict(X_test_scaled)

c:\Users\Simon R\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1631: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Iteration 1, loss = 0.36502022
Iteration 2, loss = 0.20423616
Iteration 3, loss = 0.17701338
Iteration 4, loss = 0.16709646
Iteration 5, loss = 0.16086941
Iteration 6, loss = 0.15449963
Iteration 7, loss = 0.14992940
Iteration 8, loss = 0.14591304
Iteration 9, loss = 0.14180430
Iteration 10, loss = 0.13860200
Iteration 11, loss = 0.13574425
Iteration 12, loss = 0.13330730
Iteration 13, loss = 0.13128973
Iteration 14, loss = 0.12904254
Iteration 15, loss = 0.12777221
Iteration 16, loss = 0.12655164
Iteration 17, loss = 0.12533615
Iteration 18, loss = 0.12406177
Iteration 19, loss = 0.12366992
Iteration 20, loss = 0.12379426
Iteration 21, loss = 0.12141653
Iteration 22, loss = 0.12110505
Iteration 23, loss = 0.12083408
Iteration 24, loss = 0.12020009
Iteration 25, loss = 0.11971258
Iteration 26, loss = 0.11868598
Iteration 27, loss = 0.11928993
Iteration 28, loss = 0.11783697
Iteration 29, loss = 0.11777261
Iteration 30, loss = 0.11653847
Iteration 31, loss = 0.11577925
Iteration 32, los

c:\Users\Simon R\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(


In [39]:
# Desescalando las predicciones
y_pred_descaled = y_scaler.inverse_transform(y_pred.reshape(-1, 1)).ravel()


# Calculando rsme y r2
rmse = mean_squared_error(y_test, y_pred_descaled, squared=False)*100000 #Multiplicando por 100k, para ver más facilmente el error
r2 = r2_score(y_test, y_pred_descaled)
print(f'RMSE: {rmse:.2f}')
print(f'R2: {r2:.2f}')


RMSE: 55750.65
R2: 0.76


c:\Users\Simon R\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_regression.py:492: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(
